global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'otel-collector'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'springboot-direct'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot1:8080','springboot2:8081']
