receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "springboot"
          scrape_interval: 10s
          scrape_timeout: 5s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ["springboot1:8080", "springboot2:8081"]

